### ISSUE TITLE
Non persistent files and missing MySQL root password

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [MISP/docker-misp#12]
Hello!

I have some question about your Docker Container:

1.) There is no volume in your documentation for the downloaded attachments under
`/var/www/MISP/app/files`
All attachments like malware examples, screenshots or other IOC´s are saved here. They are non-persistent in your docker configuration and will be earse by a rebuild ?!

2.) The deployment for your MySQL Server comes without a MySQL root password. 
So the root password is blank. Also you forward the MySQL Port 3306 directly to the MySQL Server. Shouldn´t  be that optional in that case ?

Is your Docker Container that one that we be also maintained in the future ?
Because there is a "docker-misp" and a "misp-docker" repository here which is very confusing.

Thanks for your help!

**Comment by ventz** [comment]
Hi @ITSEC-DACHSER 

1.) We left this up to the user - that is, the volume/storage management. If you use external bind  mounts or docker volumes ("permanent volumes"), it will remain across reboots and you can just swap out the docker image. With something like watchtower, it can even swap out the docker container for you as a new image gets pushed.

2.) Correct - Ubuntu 18.04 switched to a non-password root user by default. The port exposure is just to demonstrate that it can be exposed if access to the DB is needed, but the DB would never be forwarded exsternally/exposed. Our recommendation is not to expose the bind port at all -- and in our environment this is not enabled. This would be running the equvalent of:

```
docker run -it -d \
    -p 443:443 \
    -p 80:80 \
    ...
```

As far as the containers - the original goal of this project (started: https://github.com/harvard-itsecurity/docker-misp and was chosen as "official" to here: https://github.com/MISP/docker-misp) was to have a Dockerized version of MISP that follows the original project 100%. The goal even to date is still to follow the official MISP installation and create a parallel configuration for Docker of every add-on/new feature. The only deviation has been where something *has* to be changed to work within Docker. The other project was older/before ours, and it followed the "docker mentality" of one container per service. The feedback we received (and the main reason we started ours originally) is that users wanted something that was much more like the official project with a "single install/run" point. We have been maintaining our version for a very long time as you can see it is used by a few thousand organizations online. There are no plans to stop any time soon :)

Hope this helps.

**Comment by ITSEC-DACHSER** [comment]
Hello @ventz,

thanks for your reply.
1.) 
We use the docker volumes as you described in the documentation for the mysql data. The point that i do not understand, what about the shared community files under /var/www/MISP/app/files ? Don´t you keep them persistent in your enviroment. ?
If i will add this path to a docker volume to keep the shared community examples persistent, how can we do an upgrade to new MISP-Docker without loosing them? Because we will missing new files or folders that were added from the MISP Team in that docker volume. Cause the docker volume overlays the folder if i´m right ?

There is no subfolder for the shared community (malware) examples.


> `....
....
drwxr-sr-x   2 www-data www-data  4096 Nov 27  2018 9648
drwxr-sr-x   2 www-data www-data  4096 Jul 19  2018 971
drwxr-sr-x   2 www-data www-data  4096 Nov 29  2018 9712
drwxr-sr-x   2 www-data www-data  4096 Nov 30  2018 9728
drwxr-sr-x   2 www-data www-data  4096 Jul 19  2018 974
drwxr-sr-x   2 www-data www-data  4096 Jul 19  2018 976
drwxr-sr-x   2 www-data www-data  4096 Dec  4  2018 9823
drwxr-sr-x   2 www-data www-data  4096 Dec  4  2018 9824
drwxr-sr-x   2 www-data www-data  4096 Dec  4  2018 9825
drwxr-sr-x   2 www-data www-data  4096 Dec  4  2018 9826
drwxr-sr-x   2 www-data www-data  4096 Jul 19  2018 985
drwxr-sr-x   2 www-data www-data  4096 Dec  6  2018 9907
drwxr-sr-x   2 www-data www-data  4096 Dec  7  2018 9936
drwxr-sr-x   2 www-data www-data  4096 Dec  7  2018 9946
drwxr-sr-x   2 www-data www-data  4096 Jul 19  2018 996
drwxr-sr-x   2 www-data www-data  4096 Dec 10  2018 9978
drwxr-sr-x   2 www-data www-data  4096 Jul 19  2018 998
drwxr-sr-x   2 www-data www-data  4096 Sep  6 11:15 community-metadata
-rwxrwx---   1 www-data www-data     0 Jul 16  2018 empty
drwxrws---   2 www-data www-data  4096 Dec 18 13:11 feed-metadata
drwxr-sr-x   3 www-data www-data  4096 Jan  8 09:14 misp-decaying-models
drwxrws---   8 www-data www-data  4096 Dec 18 13:11 misp-galaxy
drwxrws---   6 www-data www-data  4096 Dec 18 13:11 misp-objects
drwxrws---   4 www-data www-data  4096 Oct 17  2018 noticelists
drwxrws---  10 www-data www-data  4096 Dec 18 13:11 scripts
drwxr-sr-x   4 www-data www-data  4096 Oct 16  2018 shadow
drwxrws--- 112 www-data www-data  4096 Dec 18 13:11 taxonomies
drwxrws---   2 www-data www-data  4096 Jul 16  2018 terms
drwxrws---   4 www-data www-data  4096 Jan  8 09:09 warninglists
/var/www/MISP/app/files#

Hope you get the point.

2.) 
Okay, this is how we've done it before and this is how we'll continue to do it.

Thanks for your help!

**Comment by ventz** [comment]
@ITSEC-DACHSER 

There are essentially two main ways of storing data within Docker:

1.) bind mounts - see: https://docs.docker.com/storage/bind-mounts/
vs
2.) volumes - see: https://docs.docker.com/storage/volumes/

On the README we use #1 (bind mounts) because that is the most popular way to just have "data" mapped into the container, but the recommended way for services / production is with #2 (volumes)

#2 (volumes) allow you to use persistent volumes, back them up, host them on s3/cloud providers/etc.
This abstracts the volume as a quasi container-like object (see: `docker volume`) which is independent of the container itself. Using this method, you can literally rebuild a docker image/pull a new version and just attach it to your storage. It would be no different than doing an MISP system/service/package upgrade in linux and maintaining your storage disk. 

Hope this helps.

**Comment by ITSEC-DACHSER** [comment]
@ventz

Yes, we use also volumes here in our deployment.
For example:

` -v /var/lib/docker/volumes/misp-files/_data:/var/www/MISP/app/files`

And yes, the data (malware samples & misp files) inside this folder is persisent, of course.

**BUT, what if there is a new script available in the next MISP Version under /var/www/MISP/app/files/script ?
I will miss that new script after image/pull to a new version, because of my volume. Right ?**

Are we the only users here that will take care about this "files" folder ?
Because there is no hint in the README that the shared malware samples are temporary.
The persistent database is just a part.

Thank you!

**Comment by iglocska** [comment]
This was definitely a short-sighted decision from our side. There's a larger rework of MISP forseen for this year that will aim to correct this and provide a better split between code and data.

**Comment by ITSEC-DACHSER** [comment]
@iglocska 
Thank you very much for your information. So we will wait for the better distribution of code and data and try the Docker version again.
