### ISSUE TITLE
build err

### ISSUE THREAD

**Issue by Kazuya720** [MISP/docker-misp#13]
build err

Collecting socketio-client==0.5.6
  Downloading socketIO-client-0.5.6.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_c41rtbv/socketio-client/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_c41rtbv/socketio-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-_c41rtbv/socketio-client/pip-egg-info
         cwd: /tmp/pip-install-_c41rtbv/socketio-client/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_c41rtbv/socketio-client/setup.py", line 6, in <module>
        README = open(os.path.join(here, 'README.rst')).read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5786: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Trolldemorted** [comment]
Did you find a solution for that problem?

**Comment by DarkZatarra** [comment]
Solution is quite easy but hard to find on internet:

export LC_ALL=C.UTF-8
PYTHONIOENCODING=utf8 pip3 install -I -r REQUIREMENTS

I don't think you need the pythonioencoding but you can just put it there.

This worked for me. I don't know what are the plans for the future but Docker file should be updated with these things if you really want to run misp-modules.

**Comment by ventz** [comment]
Trying to understand why you ran into this - that is, is your native env not C.UTF-8?

(If it's a general problem - I want to fix it. What's strange is that we have a few thousand users and no one has run in to this yet, or at least mentioned it :)...but then again, I think most have their shells/envs set with UTF-8...so that could be it)
