### ISSUE TITLE
Fully Container MISP (DB inside the container)

### ISSUE THREAD

**Issue by BrunoMCBraga** [MISP/docker-misp#17]
Hello

Is it possible to have the the $docker-root inside the container?

I would like to put this on AWS using Kubernetes but there is this external set of files.

Would you be so kind to help me with this?

Thanks

**Comment by ventz** [comment]
@BrunoMCBraga Yes - this is just a persistent volume.

If you are using Kubernetes/Docker Swarm (ECS) - you can simply have it mapped externally (be it EBS or EFS)
see: https://aws.amazon.com/blogs/compute/amazon-ecs-and-docker-volume-drivers-amazon-ebs/

If you are using Fargate, it gets a little more complicated, but I think you should be able to do it with EFS.

**Comment by ventz** [comment]
Closing this here (see README) - please open new issues at: https://github.com/harvard-itsecurity/docker-misp/issues
