### ISSUE TITLE
MISP Error Using Docker-Compose

### ISSUE THREAD

**Issue by ashim-mahara** [MISP/docker-misp#5]
It runs fine with the docker run command using the directory for mysql-db but gives following error on docker-compose.

Error:

`misp_test | 2019-04-22 05:55:57,701 CRIT Supervisor running as root (no user in config file)
misp_test | 2019-04-22 05:55:57,712 INFO supervisord started with pid 1
misp_test | 2019-04-22 05:55:58,714 INFO spawned: 'master' with pid 8
misp_test | 2019-04-22 05:55:58,715 INFO spawned: 'workers' with pid 9
misp_test | 2019-04-22 05:55:58,717 INFO spawned: 'syslog-ng' with pid 10
misp_test | 2019-04-22 05:55:58,718 INFO spawned: 'apache2' with pid 11
misp_test | 2019-04-22 05:55:58,719 INFO spawned: 'cron' with pid 12
misp_test | 2019-04-22 05:55:58,720 INFO spawned: 'misp-modules' with pid 13
misp_test | 2019-04-22 05:55:58,721 INFO spawned: 'mysqld_safe' with pid 14
misp_test | 2019-04-22 05:55:58,722 INFO spawned: 'redis-server' with pid 15
misp_test | 2019-04-22 05:55:58,769 INFO success: misp-modules entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)                                                                      
misp_test | 2019-04-22 05:55:59,132 INFO exited: mysqld_safe (exit status 0; not expected)
misp_test | 2019-04-22 05:55:59,770 INFO success: master entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                            
misp_test | 2019-04-22 05:55:59,770 INFO success: workers entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                           
misp_test | 2019-04-22 05:55:59,770 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                         
misp_test | 2019-04-22 05:55:59,770 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                           
misp_test | 2019-04-22 05:55:59,770 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                              
misp_test | 2019-04-22 05:55:59,770 INFO success: redis-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                      
misp_test | 2019-04-22 05:56:00,217 INFO spawned: 'mysqld_safe' with pid 279
misp_test | 2019-04-22 05:56:00,570 INFO exited: workers (exit status 0; expected)
misp_test | 2019-04-22 05:56:00,597 INFO exited: mysqld_safe (exit status 0; not expected)
misp_test | 2019-04-22 05:56:02,600 INFO spawned: 'mysqld_safe' with pid 454
misp_test | 2019-04-22 05:56:02,976 INFO exited: mysqld_safe (exit status 0; not expected)
misp_test | 2019-04-22 05:56:05,980 INFO spawned: 'mysqld_safe' with pid 611
misp_test | 2019-04-22 05:56:06,364 INFO exited: mysqld_safe (exit status 0; not expected)
misp_test | 2019-04-22 05:56:07,365 INFO gave up: mysqld_safe entered FATAL state, too many start retries too quickly                                                                                             
`

```version: "2"

services:
  MISP:
#    build: web
    container_name: misp_test
    image: vairavtech/misp:v1.1
    restart: unless-stopped
    ports:
       - "80:80"
       - "443:443"
       - "3306:3306"
       - "6379:6379"
    volumes:
#        - /dev/urandom:/dev/random
#        - /root/misp/docker-misp/data/misp/web:/var/www/MISP
       - /root/misp/docker-misp/test/misp-db:/var/lib/mysql
#        - /root/misp/docker-misp/certs:/etc/ssl/private
```

**Comment by ashim-mahara** [comment]
I built a custom image using your Dockerfile, please don't mind the name of the image. :)

**Comment by ventz** [comment]
@0x18katyan Sorry, sadly I am not actually too familiar with composer (when I started with Docker ~6 years ago, composer did not exist, and I ended up building my own framework for running the containers. Over time I perfected it, and by the time composer came out, I had little to no incentive to move to it). I am assuming there is some property/value that is missing in composer, since technically it should just meta markup (yaml) the run parameter properties.

You could try docker autocomposer or something like this: https://github.com/Red5d/docker-autocompose

Are you saying that this works perfectly by the way:
```
docker run -it -d \
    -p 443:443 \
    -p 80:80 \
    -p 3306:3306 \
    -v /root/misp/docker-misp/test/misp-db:/var/lib/mysql \
    airavtech/misp:v1.1
```

I suspect something else is going on because the mysqld pid is actually dying in your output. Double check your mounting/volume dir, permissions, etc.

**Comment by ashim-mahara** [comment]
@ventz Yes, the above command works fine. Essentially all I am doing is putting the above command into a docker-compose file. It shouldn't be a matter of permissions since the docker daemon is using the exact directory for the simple run.

**Comment by ventz** [comment]
@0x18katyan I just created one with our image and it seems to work:

```
% docker-compose up
Creating network "tmp_default" with the default driver
Creating tmp_misp_1 ... done
Attaching to tmp_misp_1
misp_1  | 2019-04-23 17:26:23,881 CRIT Supervisor running as root (no user in config file)
misp_1  | 2019-04-23 17:26:23,886 INFO supervisord started with pid 1
misp_1  | 2019-04-23 17:26:24,890 INFO spawned: 'master' with pid 8
misp_1  | 2019-04-23 17:26:24,894 INFO spawned: 'workers' with pid 9
misp_1  | 2019-04-23 17:26:24,899 INFO spawned: 'syslog-ng' with pid 10
misp_1  | 2019-04-23 17:26:24,903 INFO spawned: 'apache2' with pid 11
misp_1  | 2019-04-23 17:26:24,911 INFO spawned: 'cron' with pid 16
misp_1  | 2019-04-23 17:26:24,931 INFO spawned: 'misp-modules' with pid 23
misp_1  | 2019-04-23 17:26:24,936 INFO spawned: 'mysqld_safe' with pid 25
misp_1  | 2019-04-23 17:26:24,947 INFO spawned: 'redis-server' with pid 26
misp_1  | 2019-04-23 17:26:24,948 INFO success: misp-modules entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
misp_1  | 2019-04-23 17:26:25,934 INFO success: master entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp_1  | 2019-04-23 17:26:25,934 INFO success: workers entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp_1  | 2019-04-23 17:26:25,935 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp_1  | 2019-04-23 17:26:25,935 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp_1  | 2019-04-23 17:26:25,935 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp_1  | 2019-04-23 17:26:25,935 INFO success: mysqld_safe entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp_1  | 2019-04-23 17:26:26,034 INFO success: redis-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp_1  | 2019-04-23 17:26:27,430 INFO exited: workers (exit status 0; expected)
```

```
% docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                                                   NAMES
0e17a527a388        harvarditsecurity/misp   "/usr/bin/supervisor…"   13 seconds ago      Up 11 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 6379/tcp, 0.0.0.0:3306->3306/tcp, 50000/tcp   tmp_misp_1
```

Here is the docker-compile file:

```
% cat docker-compose.yml 
version: '3'

services:
  misp:
    image: harvarditsecurity/misp
    ports:
     - "443:443"
     - "80:80"
     - "3306:3306"
    volumes:
     - /docker/misp:/var/lib/mysql
```

**Comment by ventz** [comment]
@0x18katyan I am assuming the above worked for you? (Closing this issue)
