### ISSUE TITLE
Docker Build Error - UnicodeDecodeError 

### ISSUE THREAD

**Issue by JR-ship** [MISP/docker-misp#7]
When attempting to build on OSX I get this error at step 26, any recommendations? 

Step 26/45 : RUN sudo pip3 install .
 ---> Running in 5c095762a0d6
Processing /var/www/MISP/app/files/scripts/python-maec
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-e8c6zs2_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-e8c6zs2_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-e8c6zs2_/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-e8c6zs2_/setup.py", line 54, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-req-build-e8c6zs2_/setup.py", line 27, in get_long_description
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 141: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c sudo pip3 install .' returned a non-zero code: 1
bash-3.2$

**Comment by cedric-ryo** [comment]
When attempting to build on Ubuntu18.04 I get this error at step 26, any recommendations?

Step 26/45 : RUN sudo pip3 install .
 ---> Running in a5d5d4f82801
Processing /var/www/MISP/app/files/scripts/python-maec
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ibbft7ub/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ibbft7ub/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-ibbft7ub/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ibbft7ub/setup.py", line 54, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-req-build-ibbft7ub/setup.py", line 27, in get_long_description
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 141: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removing intermediate container a5d5d4f82801
The command '/bin/sh -c sudo pip3 install .' returned a non-zero code: 1

**Comment by ventz** [comment]
@juanaldreagan @cedric311 Sorry for the delay - I wanted to replicate this. 

It seems to be actually a problem with the MAEC Project  (https://github.com/MAECProject/python-maec.git)

Could you please open an issue there -- you are welcome to link this issue.

For now, if you want we can temporarily remove the MAEC module. Just comment out in the Dockerfile:

```
WORKDIR /var/www/MISP/app/files/scripts/python-maec
RUN sudo pip3 install .
```

**Comment by ventz** [comment]
Fixed upstream.
